server {
  listen 80;
  listen [::]:80;
  server_name __PHP_DOMAIN__;

  root /var/www/php-site-c/public;
  index index.php index.html;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php__PHP_VERSION__-fpm.sock;
  }

  location ~ /\.ht {
    deny all;
  }
}
